services:
  marble_api:
    image: python:3.13-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "pip install -e .[dev,test] && fastapi dev marble_api --host 0.0.0.0"]
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    ports:
      - 8000:8000
  mongo:
    image: mongo:5.0.4
